### ISSUE TITLE
Simplify logoutURL code

### ISSUE THREAD

**Issue by b1conrad** [Picolab/fully-sharded-database#58]
The code is a hold-over from very early attempts at de-authentication.

**Comment by b1conrad** [comment]
This is a consequence of sharding. The logout URL is something that the main pico (the one representing all of the entities as a collection) is able to compute. Each entity cannot do so, and therefore does a
```
ctx:query(wrangler:parent_eci(),"byu.hr.oit","logout",{"_headers":_headers})
```
to inquire of the parent pico, because that's the topology chosen for this experiment: every entity is a direct child of the root pico.

For historical reasons (before developing the html.byu module), the root pico computes a snippet of HTML, but could simply compute the URL
```
    logout = function(_headers){
      netid = html:cookies(_headers).get("netid")
      eci = wrangler:channels("byu-hr-login").head().get("id")
      <<#{meta:host}/sky/event/#{eci}/none/byu_hr_login/logout_request>>
    }
```
Because it currently returns a snippet of HTML, every ruleset that inquires has to extract the URL like so:
```
url = logout(_headers).extract(re#location='([^']*)'#).head()
```
And, it is currently required to pass this into the `html:header` function as the third positional argument (after the page title and scripts/styles for the `head` tag).

**Comment by b1conrad** [comment]
First step will be to compute just the URL in the parent pico ruleset and remove the `extract()` function call in the entity pico rulesets.

**Comment by b1conrad** [comment]
Code change made. Thinking about deploying it. It breaks the boilerplate for apps, so going to have to find all of those and make the same change.

**Comment by b1conrad** [comment]
Thinking that I'll make a more dramatic change instead. Reverting the code changes.

**Comment by b1conrad** [comment]
Plan is to have the `byu.hr.login` ruleset compute the logout URL and store it in a cookie. Then the `html.byu` module can just retrieve it from the headers, which it gets anyway, as a named argument. Since a URL can't contain a semi-colon, this should work. Research and testing will now ensue.

**Comment by b1conrad** [comment]
Oh, hit a snag. All of the cookies so far have `Path=/c` but to set cookies (and redirect), the event has to be called with the standard sky event syntax. And the pages are called with the newer `/c/ECI` paths, and they're the ones that need the logout URL. Sigh.

Since this is the only web application running on the server, it should be okay to use `Path=/` and that should solve this problem.

**Comment by b1conrad** [comment]
Tried simplifying in a [boilerplate](https://raw.githubusercontent.com/b1conrad/PicoStack/main/languages/krl/boilerplate.krl) ruleset. Seems to work. Can now repeat this in all app rulesets.

**Comment by windley** [comment]
I would love to think through how individual picos can be responsible for their own auth and de-auth.

**Comment by b1conrad** [comment]
Yeah none of the pico-based systems I've done are completely satisfying. In every case, I find myself telling people, "this is _your_ pico." But, they don't really own it. I've just created yet another silo.

**Comment by b1conrad** [comment]
Things that can be done in the `html.byu` module are now done therein. This effort closed with a series of commits culminating with [this one](https://github.com/Picolab/fully-sharded-database/commit/24fda5ed80179b4c904f5b1cd6ad4adb2cca7668).
